name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: [ '5432:5432' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      - name: Instalar dependências
        run: |
          pip install pipenv
          pipenv sync -d
      - name: Rodar flake8
        run: |
          pipenv flake8 .
          pipenv pytest --cov=pypro
      - name: Codecov
        env:
          CODECOV_TOKEN: 'dd284f1f-ad45-4529-9d3f-d5ae323e6a1d'
        run: |
          pipenv codecov
          echo Add other actions to build,
          echo test, and deploy your project.
